---
- hosts: apache
  become: yes
  tasks:
    - name : Install apache
      yum:
        name: httpd
        state: present
    - name: Copy local file t deployment directory
        copy:
          src: index.html
          des: /var/www/html/

    - name: start and enable apache
        service:
          name: httpd
          state: started
          enabled: yes


